# Generated by Django 4.1 on 2022-10-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_posteo_imagen_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='imagen_posteo',
        ),
    ]
