# Generated by Django 4.1 on 2022-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_posteo_imagen_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen_posteo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
