# Generated by Django 4.1 on 2022-10-02 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('texto', models.CharField(max_length=2000)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='remitente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
