# Generated by Django 4.1 on 2022-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='destinatario',
            field=models.CharField(max_length=60),
        ),
    ]
