# Generated by Django 4.1 on 2022-10-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChat', '0002_alter_mensajes_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='remitente',
            field=models.CharField(max_length=60),
        ),
    ]
