# Generated by Django 4.1 on 2022-10-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChat', '0004_mensajes_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
